apiVersion: v1
kind: Service
metadata:
  name: lists-frontend
  labels:
    app: lists-frontend
  namespace: default
spec:
  ports:
    - port: 80
      targetPort: 80
      name: lists-frontend0
  selector:
    app: lists-frontend
