export const OPEN_SERIES_LIST = 'OPEN_SERIES_LIST';
export const OPEN_SIGN_IN = 'OPEN_SIGN_IN';
export const OPEN_SERIES_ITEM = 'OPEN_SERIES_ITEM';
export const SET_JWT = 'SET_JWT';
export const LOGIN_USER = 'LOGIN_USER';
export const SERIES_LIST_SET_LOADING_STATE = 'SERIES_LIST_SET_LOADING_STATE';
export const SERIES_ITEM_SET_LOADING_STATE = 'SERIES_ITEM_SET_LOADING_STATE';
export const BOOK_SET_LOADING_STATE='BOOK_SET_LOADING_STATE';
export const SERIES_ITEM_ADD_BOOK = 'SERIES_ITEM_ADD_BOOK';
export const OPEN_SERIES_ITEM_SHOW = 'OPEN_SERIES_ITEM_SHOW';
export const SET_LIST_TYPE = 'SET_LIST_TYPE';
export const OPEN_READ_LIST = 'OPEN_READ_LIST';

export const SET_BOOK_LIST_RELOAD = 'SET_BOOK_LIST_RELOAD';

// WatchList.Title
export const OPEN_TITLES_LIST = 'OPEN_TITLES_LIST';
export const OPEN_TITLE = 'OPEN_TITLE';
export const OPEN_ADD_TITLE = 'OPEN_ADD_TITLE';
export const TITLE_ADD_SET_RESULT = 'TITLE_ADD_SET_RESULT';
export const OPEN_UPDATE_TITLE = 'OPEN_UPDATE_TITLE';

// ReadList.Author
export const OPEN_AUTHOR_LIST = 'OPEN_AUTHOR_LIST';
export const OPEN_AUTHOR = 'OPEN_AUTHOR';
export const OPEN_AUTHOR_ADD = 'OPEN_AUTHOR_ADD';

// ReadList.Books
export const OPEN_BOOK_LIST = 'OPEN_BOOK_LIST';
export const OPEN_BOOK = 'OPEN_BOOK';
export const SAVE_BOOK_EDIT = 'SAVE_BOOK_EDIT';
export const OPEN_ADD_BOOK = 'OPEN_ADD_BOOK';
export const OPEN_BOOK_V2 = 'OPEN_BOOK_V2';
export const OPEN_UPDATE_BOOK = 'OPEN_UPDATE_BOOK';

// Series
export const OPEN_SERIES_ADD = 'OPEN_SERIES_ADD';
export const OPEN_SERIES_EDIT = 'OPEN_SERIES_EDIT';